### ISSUE TITLE
I would like to contribute

### ISSUE THREAD

**Issue by ioggstream** [json-ld/yaml-ld#1]
Dear folks,

I would be happy to contribute, since I'm working on the YAML media type registration  https://ietf-wg-httpapi.github.io/mediatypes/draft-ietf-httpapi-yaml-mediatypes.html

and we already have an issue related to the registration of [ld+yaml media type](https://github.com/ietf-wg-httpapi/mediatypes/issues/8).

cc: @eemeli

**Comment by gkellogg** [comment]
> @gkellogg already in the json-ld community. Thanks++

Yes, I checked before adding you to the YAML-LD Team, the note was for anyone else that wants to join the team.

**Comment by VladimirAlexiev** [comment]
@gkellogg Please add me too. I applied for CG membership (I'm in several CGs so that should be able to go through quickly)

**Comment by gkellogg** [comment]
> @gkellogg Please add me too. I applied for CG membership (I'm in several CGs so that should be able to go through quickly)

Done.

**Comment by juusoautiosalo** [comment]
@gkellogg I am interested in contributing where I can, so would like to join as well. I just sent a request to join the CG. (This would be the first standardization activity for me.)

Thanks to everyone for making this happen!

**Comment by gkellogg** [comment]
Welcome! The next meeting will be in two weeks on July 6th at 18:00 UTC. In the meantime, work proceeds on the existing issues. We're actively looking for new Use Cases, so please generate issues as appropriate.
