### ISSUE TITLE
`YAML-LD with node anchors` vs `YAML-LD: Anchors & Aliases` examples identical

### ISSUE THREAD

**Issue by anatoly-scherbakov** [json-ld/yaml-ld#101]
This shows a need to refactoring, I believe.

**Comment by gkellogg** [comment]
Inevitably, an example showing an Alia’s must also have an anchor for it to make sense. Not necessarily the reverse, though.

**Comment by anatoly-scherbakov** [comment]
The second incarnation of this example is replaced by a link to its first incarnation at https://github.com/json-ld/yaml-ld/pull/100, closing this.
