### ISSUE TITLE
Test: `#cr-comments-1-positive` is probably not applicable

### ISSUE THREAD

**Issue by anatoly-scherbakov** [json-ld/yaml-ld#116]
Manifest:

```json
    {
      "@id": "#cr-comments-1-positive",
      "@type": ["jld:PositiveEvaluationTest", "jld:ExpandTest"],
      "name": "Various comment forms",
      "purpose": "Comments are white space.",
      "req": "must",
      "input": "basic/cr-comments-1-positive-in.yamlld",
      "expect": "basic/cr-comments-1-positive-out.yamlld"
    }
```

This test asks us to do an expansion for `cr-comments-1-positive-in.yamlld` and compare the result against `cr-comments-1-positive-out.yamlld`.

In the current state of the spec, we do not define an `expand()` operation that would be different from JSON-LD expansion, do we?

I am working on a YAML-LD plugin for https://github.com/rdflib/rdflib and there is no such operation there, there is only YAML-LD parsing into an RDF graph or export of a graph as YAML-LD.

**Proposal.** Use `.nq` output instead of `.yamlld` and compare triples resulting from parsing the file.

**Comment by anatoly-scherbakov** [comment]
## Upd (after some thought)

I guess my statement above is incorrect; `expand()` is an operation specified by JSON-LD API, thus a conforming implementation must have that operation. I will have to write a separate library for this purpose, something like this:

```python
import yaml_ld

yaml_ld.expand(…)
```

**Comment by gkellogg** [comment]
Right, that's why the test type includes `jld:ExpandTest`, which indicates the algorithm to use. Of course, comments will be removed in the change to the Internal Representation.
