### ISSUE TITLE
Consider `extractAllScripts` flag in `expand()` API as a method to handle YAML-LD Streams

### ISSUE THREAD

**Issue by anatoly-scherbakov** [json-ld/yaml-ld#119]
Initially, this flag allows the extraction of multiple JSON-LD documents from an HTML document. Can it also be used for extracting individual entries from a YAML stream?

**Comment by gkellogg** [comment]
Yes, I think that’s reasonable. The result would be much like that for embedded JSON-LD in HTML, with the results effectively merged together.

**Comment by anatoly-scherbakov** [comment]
I think that's done.
