### ISSUE TITLE
Information about John Lennon is incorrect

### ISSUE THREAD

**Issue by anatoly-scherbakov** [json-ld/yaml-ld#136]
@anatoly-scherbakov I have a silly concern, but let's honor the life of a great man:
John was married to Cynthia for just 6 years, then married Yoko for the rest of his life.

So can you change the spouse to:
http://dbpedia.org/resource/Yoko_Ono (born 1933-02-18)

_Originally posted by @VladimirAlexiev in https://github.com/json-ld/yaml-ld/issues/132#issuecomment-2036421751_

**Comment by TallTed** [comment]
Could we not recognize both of John's spouses?

Both Cynthia and Yoko were married to John, and Cynthia was the mother of their son Julian Lennon, while Yoko was the mother of Sean Taro Ono Lennon (and of Kyoko Chan Cox, with her first husband, American film producer and art promoter Anthony Cox).

This change feels a lot like picking a winner, which I don't think any of those involved would appreciate.

(If the data model being exhibited can't handle multiple spouses, then I suggest the example be changed to people who only ever had one spouse.)

**Comment by gkellogg** [comment]
> This change feels a lot like picking a winner, which I don't think any of those involved would appreciate.

In my experience, the first spouse rarely appreciates being replaced by a second spouse. I think it is the final spouse that is the most important historically, while the previous spouses may not be more than a footnote in history. If you were to ask John who his wife was, I think it's only mention Yoko, unless the context were related to Julian, in which case Cynthia would more likely be referred to as "my wife at the time" or something similar.

In any case, the purpose of the example is to not go through the complexities of information architecture, but how to simply represent YAML-LD in HTML, so the simpler the better.

**Comment by gkellogg** [comment]
I've hidden the comment, as you find it offensive (although I don't really understand why). The point is, that it is a common choice when modeling things, and if I were to create a simple example that highlighted my own relationship, I would focus on my current relationship, and not former.

Given that this seems to be contentious, perhaps choosing an example that doesn't have such ambiguity and focuses on the way that a simple YAML-LD document can be shared in HTML is the way to go.

**Comment by anatoly-scherbakov** [comment]
I am not in the context, I am very much uneducated in terms of Lennon's biography — but just added both in my PR.

**Comment by anatoly-scherbakov** [comment]
I suppose we can close this issue.
