### ISSUE TITLE
YAML LD media type and profiles

### ISSUE THREAD

**Issue by VladimirAlexiev** [json-ld/yaml-ld#14]
We need to apply for `application/ld+yaml` media type.
@ioggstream "I'm working on the YAML media type registration https://ietf-wg-httpapi.github.io/mediatypes/draft-ietf-httpapi-yaml-mediatypes.html and we already have an issue related to the registration of https://github.com/ietf-wg-httpapi/mediatypes/issues/8".

In addition, it seems clear to me that we'll need various YAML-LD **profiles**, eg as per #6 by @pchampin . See https://www.w3.org/TR/dx-prof-conneg/

**Comment by ioggstream** [comment]
I need some feedback from all of you on the yaml fragment identifier registration 
https://github.com/ietf-wg-httpapi/mediatypes/pull/47

If the YAML fragid definition works for yaml-ld, then we can just reference the IETF document. Otherwise there will be some work to do to define a specific  fragment identifier for yaml-ld.

About the media type registration, I think that if we have something that is highly compatible with ld+json, it's ok to register yaml-ld as `ld+yaml`. Otherwise we should probably leave `ld+yaml` for the subset of highly interoperable functionalities and declare a new format (e.g. ldplus+yaml, ... )

**Comment by gkellogg** [comment]
I think we're going to need to consider different profiles. YAML provides a number of facilities that JSON does not (datatypes and fragment identifiers, for example). A "Base" level profile should restrict itself to strict JSON transcoding capability. We may consider an "extended" profile that allows for more use of these features, but the consequences for transcoding to JSON and maybe CBOR can get intense. I'd say that the group should focus on the "Base" level and consider an extended profile subsequently.

**Comment by ioggstream** [comment]
@anatoly-scherbakov about YAML fragments, the current PR proposal supports the following patterns

```
file.yaml#*alias-node
file.yaml#/json/path
file.yaml# 
```

YAML alias nodes are identified according to YAML spec and YAML media types document aims at not creating inconsistencies or constraints on how YAML works, nor how it can evolve.

> in an arbitrary YAML document where anchors are not set nothing can be referenced, if I understand the idea correctly.

This the reason for https://github.com/ietf-wg-httpapi/mediatypes/pull/47 that arose after discussing with CBOR folks.

**Comment by anatoly-scherbakov** [comment]
Oh I see. Thank you for the clarification! This looks interesting. @ioggstream

**Comment by ioggstream** [comment]
I think you all can be interested in the associated discussion https://github.com/ietf-wg-httpapi/mediatypes/issues/41 cc: @anatoly-scherbakov @VladimirAlexiev

**Comment by VladimirAlexiev** [comment]
@gkellogg thanks for the PR! I commented in just 1 place.

@ioggstream Given your https://github.com/ietf-wg-httpapi/mediatypes/pull/47, are you happy with closing this issue? It also talks about fragment identifiers, but we better move this to another issue.

**Comment by gkellogg** [comment]
@VladimirAlexiev the question on namespace deserves its own issue. I'm coming around to having a /ns/yaml-ld namespace for YAML-LD specific profile IRIs as being the least surprise, but we should track that as a CG decision.
