### ISSUE TITLE
YAML versions

### ISSUE THREAD

**Issue by VladimirAlexiev** [json-ld/yaml-ld#21]
Which YAML versions should YAML-LD support?
- relevant versions could include https://yaml.org/spec/1.0, https://yaml.org/spec/1.1, https://yaml.org/spec/1.2.2/
- But YAML is pretty stable: 12 years between 1.2.1 and 1.2.2 (https://yaml.com/blog/2021-10/new-yaml-spec/), so maybe just the latest one is relevant
- 1.2.2 says it's just an editorial rewrite of 1.2.1, but some tags have been withdrawn, and more are pending withdrawal (eg for datetime literals)

**Comment by ioggstream** [comment]
MUST 1.2.2

MAY some sensible features of YAML 1.1

**Comment by ioggstream** [comment]
> "Cannot be guaranteed" is troubling.

Theoretically, you must parse YAML document with a YAML parser, and a JSON document with a JSON document.
iiuc trouble should arise only  when there's a JSON document that cannot be mapped to a YAML representation graph.

> Should we worry about this potential future YAML 1.3 version?

My opinion is that , given the implementation base,  this won't happen. OTOH in [mediatype](https://github.com/ietf-wg-httpapi/mediatypes/blob/main/draft-ietf-httpapi-yaml-mediatypes.md) we are just relying on the fact that JSON data and document structures are a subset of YAML's ones.

**Comment by ioggstream** [comment]
I'm stubbing a PR based on the YAML work:

- this document is based on YAML 1.2.2
- the mediatype registration is related to YAML in general and not on a specific version
- people that cares about version, SHOULD start their documents with `%YAML X.Y`
