### ISSUE TITLE
File extension

### ISSUE THREAD

**Issue by juusoautiosalo** [json-ld/yaml-ld#25]
JSON-LD uses `.jsonld` as the (recommended) file extension as can be seen from the [IANA considerations and elsewhere in the specification](https://www.w3.org/TR/json-ld/#iana-considerations). So I would like to bring up an obvious question (because I am selecting the "main" file extension for a [project](https://github.com/twinbase/twinbase)):

## What will be the (recommended) file extension for YAML-LD?

I suggest `.yamlld` for consistency and the "no surprises" principle.

Previous materials on the topic:
- @gkellogg used `.ymld` in an example in this comment: https://github.com/json-ld/yaml-ld/issues/8#issuecomment-1140292068 
- https://github.com/json-ld/yaml-ld/issues/14 has used just plain `.yaml`.
  - (The upcoming IANA media type application also apparently has to define a file extension?)

**Comment by gkellogg** [comment]
".jsonld" instead of ".json" for `application/ld+json` would imply ".yamlld" instead of ".yaml" for `application/ld+yaml`. This should go in the media-type application, which is typically part of the spec.
