### ISSUE TITLE
Security, interoperability and IANA considerations

### ISSUE THREAD

**Issue by ioggstream** [json-ld/yaml-ld#29]
## I expect

the document to have:

- [x]  security consideration
- [x] interoperability considerations
- [x] iana considerations #27

**Comment by gkellogg** [comment]
Does #27 satisfy these requirements at this point? Does YAML have additional requirements we haven't cited?

**Comment by ioggstream** [comment]
I just added placeholders for the other section. Then we need to populate them.

For #27 I think it's a good starting point and that can be merged. As long as we edit the document, we'll surely re-organize and optimize stuff (if you see the YAML media type work, there are have been various editorial changes).

**Comment by ioggstream** [comment]
Closed via #27 #30
