### ISSUE TITLE
Work on YAML-LD

### ISSUE THREAD

**Issue by gkellogg** [json-ld/yaml-ld#3]
On the w3c/json-ld-syntax w3c/json-ld-syntax#389 proposes advancing work on YAML-LD. I was not able to transfer the issue to this repository, but further discussion and votes in support of starting the initiative in the JSON-LD CG should be voiced here. Given sufficient support, we'll create a yaml-ld repository for work to procede.

**Comment by anatoly-scherbakov** [comment]
@pchampin this is an interesting idea but I'd say that the required space character is a great irregularity introduced to the syntax, and is a potential source of mistakes.

It might be interesting to use YAML tags for something in YAML-LD context, but I have no idea how at present. `$type` seems to work fine to assign RDF types to nodes. I do not have any other ideas.

**Comment by pchampin** [comment]
@anatoly-scherbakov 
> @pchampin this is an interesting idea but I'd say that the required space character is a great irregularity introduced to the syntax, and is a potential source of mistakes.

I agree, unfortunately.

> It might be interesting to use YAML tags for something in YAML-LD context, but I have no idea how at present.

I created a dedicated issue for this: #6.

**Comment by VladimirAlexiev** [comment]
Closing this. If you've made important remarks above, please post them as separate issues.
In particular @gkellogg https://github.com/json-ld/yaml-ld/issues/3#issuecomment-1137630441, and maybe @pchampin ?
