### ISSUE TITLE
Choose prefix character to replace @

### ISSUE THREAD

**Issue by anatoly-scherbakov** [json-ld/yaml-ld#55]
As an architect of a YAML-LD aware system and a developer, I am a bit uncomfortable about having my users write JSON-LD @-keywords and have to quote them because that would mean additional effort. I would rather prefer some other prefix character from ASCII character set.

## Choice of prefix characters

| @id | Notes | Resolution
| --- | --- | --- |
| `@id` | Is [reserved](https://yaml.org/spec/1.2.2/#rule-c-directive). | x |
| `id | Is [reserved](https://yaml.org/spec/1.2.2/#rule-c-directive). | x |
| ~id | Works |  |
| !id | Used for [tags](https://yaml.org/spec/1.2.2/#tag-handles) | x |
| #id | Used for [comments](https://yaml.org/spec/1.2.2/#rule-c-nb-comment-text) | x |
| $id | Works | x |
| %id | Used for [directives](https://yaml.org/spec/1.2.2/#rule-c-directive) | x |
| ^id | Works |  |
| &id | Used for [anchors](https://yaml.org/spec/1.2.2/#anchors-and-aliases) | x |
| *id | Used for [aliases](https://yaml.org/spec/1.2.2/#anchors-and-aliases) | x |
| -id | Works, but is confusable with lists: `- id` | x |
| +id | Works |  |
| _id | Works but is confusable with blank nodes (#57) | x |

Also, `_` in Python means private or internal things so I am subconsciously against that :)

I suggest using `$` for the Convenience Context. This character also is good for JS: `something.$type` is workable in that language.

The users however may do whatever they want. For instance, users might want something like this:

```yaml
=: 🏠:cat
∊: 🐱
🏷️:
  🇺🇸: Ray
```

I won't stop them. Our `$` is really just a way to trigger everyone's imagination.

**Comment by VladimirAlexiev** [comment]
A good analysis what chars are suitable for #51

**Comment by gkellogg** [comment]
Discussed in the TPAC F2F and [resolved to close as won't fix](https://json-ld.org/minutes/2022-09-12/#resolution-2).
