### ISSUE TITLE
Links to sections of YAML spec do not work

### ISSUE THREAD

**Issue by anatoly-scherbakov** [json-ld/yaml-ld#61]
At PR #59, @gkellogg had introduced links to sections of the YAML specification which define particular terms of the spec.

## Why?

`[[YAML]]` is dereferenced by ReSpec as per [SpecRef](https://www.specref.org/?q=yaml) into http://yaml.org/spec/1.2/spec.html. Thus, `YAML#92-streams` is converted into http://yaml.org/spec/1.2/spec.html#92-streams.

Which does not work as expected, instead it redirects to https://yaml.org/spec/1.2.2/ and the fragment identifier is lost.

## What?

I would like to propose to change the YAML spec link to version 1.2.2 instead of 1.2. That should alleviate the redirect.

**Comment by gkellogg** [comment]
We can change it in localBiblio n the respec config.
