### ISSUE TITLE
Terminology not normative? 

### ISSUE THREAD

**Issue by ioggstream** [json-ld/yaml-ld#67]
## Question

afaik Terminology in specifications is normative, since it affects the interpretation of the document. 
https://json-ld.github.io/yaml-ld/spec/#terminology 

Which is the meaning of "not normative" in W3C drafts?

**Comment by gkellogg** [comment]
Terminology in [JSON-LD 1.1](https://www.w3.org/TR/json-ld11/#terminology) is also informative. Generally, we don't make normative statements in the terminology section, just provide definitions (or references) for the terms used in other normative sections. In this case, almost all terms are defined externally. Where it defines a normative concept, it is defined normatively in another suction such as [4.4 Streams](https://json-ld.github.io/yaml-ld/spec/#streams).

In W3C drafts, "not normative" is "informative".

**Comment by ioggstream** [comment]
Ok, thanks :)
